### ISSUE TITLE
OpenID Connect Tests

### ISSUE THREAD

**Issue by arscan** [fhir-crucible/crucible_smart_app#51]
Currently there are no OpenID Connect tests. We will need to decide where these should be placed.  Perhaps they are best suited within existing launch test sequences.

**Comment by jricher** [comment]
Right now, all of the OAuth/OIDC functions are embedded in the launch sequences. We don't have anything that separately does OAuth or ODIC in positive tests, let alone anything in negative tests. However, the rest of the test framework needs a positive result from the launch sequence in order for the test to continue. It might make more sense to add both additional checks within the launch sequences as well as further tests, particularly for negative results, outside of the launch sequence.
