### ISSUE TITLE
Transport level tests

### ISSUE THREAD

**Issue by arscan** [fhir-crucible/crucible_smart_app#53]
Add TLS tests, if possible.  This is not something that we did in Crucible, so we do not currently have any tests for this.

**Comment by srmoore** [comment]
What sort of level of tests are you thinking here? A 'simple' make sure the connection uses TLS? Or enforce a certain level of TLS (e.g. 1.2).   From a quick look through the FHIR spec, I only see "Should use TLS/SSL", not any specific version.

**Comment by arscan** [comment]
As you found, FHIR isn't very opinionated about security.  The current direction is to basically use SMART on FHIR's recommendation (http://docs.smarthealthit.org/authorization/best-practices/), which is TLS 1.2 + maybe certain cipher suites.  OAuth also states some requirements, but in quickly looking they seem consistent with SMART's recommendation.  I'd say we could check up to three levels:

1) using TLS/SSL
2) using TLS 1.2
3) using cipher suites recommended by NIST FIPS SP 140-2, Annex A.  

We could put 3 (and maybe 2) as warnings.  I think the first thing to do is figure out what we can test in Ruby using the libraries we currently have (some of this might happen already, as the client is smart enough to reject MITRE's MITM TLS inspection).  Then we can figure out where we want to put the tests ('inline' with every request, or should we just isolate TLS checking to certain requests so those failures are more isolated).

**Comment by srmoore** [comment]
So it looks like the libraries in use (i.e. rest-client) are built on top of the Ruby OpenSSL libs. We'll get finer control by using the OpenSSL stuff directly to open a socket and do the handshake, verifying that servers reject when we try to connect with a lower TLS version etc.

**Comment by arscan** [comment]
Implemented in #113.  Thanks!
