### ISSUE TITLE
Refresh tokens and token introspection

### ISSUE THREAD

**Issue by arscan** [fhir-crucible/crucible_smart_app#56]
We are using token introspection as a means to confirm that token timeouts are correct.  However, token introspection is not required by SMART.  For those servers that do not support introspection, add dialog to manually confirm proper timeouts.  Rename sequence to be timeout related (or place within one of the previous launch sequences). See #52

**Comment by jricher** [comment]
Currently we're introspecting access tokens in the test, this can be expanded to refresh tokens as well.

**Comment by arscan** [comment]
Manual confirmation for timeouts added in 2a5561b51a3510cc1990229137a1c66f65fce4d0

Refresh token introspection added in #129
