### ISSUE TITLE
Add additional test or assertions to token exchange

### ISSUE THREAD

**Issue by arscan** [fhir-crucible/crucible_smart_app#69]
On token exchange, we should test this from SMART on FHIR spec:  

```The authorization server’s response MUST include the HTTP “Cache-Control” response header field with a value of “no-store,” as well as the “Pragma” response header field with a value of “no-cache.”```

We could either expand the current test regarding the validity of the response (don't just test for 201, but also for headers), or add in another test that just tests the headers.

Make sure we add this for both Standalone and EHR Launches.

**Comment by kjmahalingam** [comment]
Resolved in #72.
