### ISSUE TITLE
fhir_models Documentation

### ISSUE THREAD

**Issue by aviars** [fhir-crucible/crucible_smart_app#81]
Include 1-3 console examples in the `README.md` here

https://github.com/fhir-crucible/fhir_dstu2_models/
https://github.com/fhir-crucible/fhir_models/

**Comment by jawalonoski** [comment]
This was fixed with https://github.com/fhir-crucible/fhir_dstu2_models/pull/7 and https://github.com/fhir-crucible/fhir_models/pull/46

**Comment by aviars** [comment]
Thanks for adding to the README @jawalonoski
